[package]
name = "qst"
version = "1.0.0"
edition = "2021"
description = "Quick Serve This: Simple serve meant for development."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
